# file path: ~/.config/hypr/conf/exec.conf

# Status Bar (AGS)
exec-once = ags quit & ags run ~/.config/ags/widgets/bar/app.ts

# Hypr Apps
exec-once = hyprpaper # Wallpaper Manager
exec-once = hypridle # Idle Manager
exec-once = hyprsunset # Night Mode

# Notification Daemon
exec-once = swaync &

# Clipboard Manager
exec-once = copyq

